name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docker:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose run application