name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build . -t modern-cpp

      - name: test
        run: docker run modern-cpp sh -c "./build/test/GreeterTests"
