name: Documentation

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and publish documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '**/cpm_modules'
          key: cpm-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          brew install doxygen
          pip3 install jinja2 Pygments

      - name: Build
        run: |
          cmake -Sdocumentation -Bbuild -DCPM_SOURCE_CACHE=$(pwd)/cpm_modules
          cmake --build build --target GenerateDocs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doxygen/html
